#!/usr/bin/env bash

# Remove all containers
docker stop $(docker ps -q)
docker rm   $(docker ps -aq)

# Remove all volumes
docker volume prune -f

# Remove user-defined network
docker network prune -f
