#!/usr/bin/env bash

ROOT_DIR="$(cd $(dirname "${BASH_SOURCE[0]}") && pwd)"
SITES_DIR="$ROOT_DIR/sites"

# :Latest leads to problems on different systems
# due to different versions
HTTPD_VERSION="2.4.34"

docker network create --driver bridge reverse-proxy-net

# reverse proxy
docker run -dit \
  --mount type=bind,source=$ROOT_DIR/conf,destination=/usr/local/apache2/conf \
  --mount type=bind,source=$ROOT_DIR/cert,destination=/usr/local/apache2/cert \
  --mount type=bind,source=$SITES_DIR/default,destination=/usr/local/apache2/htdocs \
  --network reverse-proxy-net \
  -p80:80 -p443:443 \
  --name reverseproxy httpd:$HTTPD_VERSION

# site 1
 docker run -dit \
  --network reverse-proxy-net \
  --name site1 site1

  # site 2
  docker run -dit \
   --mount type=bind,source=$SITES_DIR/site2,destination=/usr/local/apache2/htdocs \
   --network reverse-proxy-net \
   --name site2 httpd:$HTTPD_VERSION
